### ISSUE TITLE
ModelScale

### ISSUE THREAD

**Issue by konstander** [yoship1639/ValheimVRM#1]
Parameter "ModelScale" in file settings_NAME.txt not working!

**Comment by yoship1639** [comment]
Thank you for your report.
It worked fine with my settings, so it's possible you misconfigured somewhere.
Does the NAME parameter in settings_NAME.txt exactly match the name of the player in Valheim?
Or have you edited the comments? The // line is a comment, so if you edit the Default=1.1 part, nothing will work.
Or have you placed settings_NAME.txt in the correct path?

**Comment by konstander** [comment]
I did not correct the comment, everything is clear with the syntax.
I correct the value for example: "Default=1.5" or "Default=1.8" (without quotes).
Nothing will work. 

Additional question. In the game, when I put on the armor, it is not visible - this is how it should be, ok. But when I put on the belt (additional weight), it is displayed on the character model in the chest area in an enlarged view ...
Anyway, thanks for the mod, I wish you success.

**Comment by yoship1639** [comment]
OK,
Please check ver1.0.3 as I have just updated the settings related.
The problem with the belt being displayed has also been fixed.

[https://github.com/yoship1639/ValheimVRM/releases/tag/ver1.0.3](https://github.com/yoship1639/ValheimVRM/releases/tag/ver1.0.3)

**Comment by konstander** [comment]
> OK,
> Please check ver1.0.3 as I have just updated the settings related.
> The problem with the belt being displayed has also been fixed.
> 
> https://github.com/yoship1639/ValheimVRM/releases/tag/ver1.0.3

Everything is fine. GJ!
