### ISSUE TITLE
update

### ISSUE THREAD

**Issue by astro5743** [yoship1639/ValheimVRM#10]
御世話に成ります。
ValheimがアプデされBepInExPackもアプデしないと起動出来ない為にアプデしました。
しかしながら、v1.0.10,v1.0.11の時同様にゲーム開始数十分で重くなりカクカク状態に陥ります。
vrmが原因なのかは素人の私には分かりませんが、以前と時間的にも動作的にも似ているので確認願います。

**Comment by yoship1639** [comment]
#11 と同様のトピックのためこちらのissueは閉じさせていただきます
