### ISSUE TITLE
The mod attempts to load settings from a path with hardcoded backslash '\', breaking cross-platform compatibility

### ISSUE THREAD

**Issue by BeryllArgent** [yoship1639/ValheimVRM#17]
[Settings.cs Line 12](https://github.com/yoship1639/ValheimVRM/blob/db2c0b5df0d64f1c6ada1974a9aeae4263221d42/ValheimVRM/Settings.cs#L12) always inserts a backslash, regardless of what operating system the game is running on.

Since the game is cross-platform and also runs on Linux, this causes the problem that the settings file can not be found where it should be.

Replacing the backslash with just a slash '/', System.IO.Path.DirectorySeparatorChar, or using the Path.Combine function would easily fix this and still work on Windows just as well.
I can create a pull request if desired.

**Comment by Isaiahmag** [comment]
I was wondering why it wouldn't work.

**Comment by yoship1639** [comment]
Thanks for the report.
I fixed it in ver 1.1.1.
