### ISSUE TITLE
1.1.1 ModelOffsetY float glitch

### ISSUE THREAD

**Issue by foazy** [yoship1639/ValheimVRM#19]
When I increase ModelOffsetY in settings_player to a value above 0.00, the player model will float + ascend upwards into the air. I've troubleshooted by reinstalling Valheim, but it seems to be ModelOffsetY causing the issue.

This was not happening in previous versions however, and seems to be exclusive to 1.1.1; In the meantime, I'll play the older versions.

(Thank you so much for this incredible mod, by the way! This has to be my favorite mod of all time. 😄❤️)

**Comment by LArtDesChOiX** [comment]
Yeah, i comfirm with Foazy. Bug in the Offset Y in 1.1.1, perfect in 1.1.0, but weapons vibrate in many skin ahah.
Thanks for the info foazy, and thanks for the MOD yoship, i really love it ;)
Good luck.

**Comment by Ariexe** [comment]
Can confirm I also get this bug. would like to fix this soon, my feet are a foot in the ground.

**Comment by KuraiKitsune** [comment]
I love this mod. Also seeing feet sink into the ground while walking and sitting. Y offset also ascending to the sky.
Thank you for the MOD <3
https://i.gyazo.com/0b0766e1a596516723df1f12bcbff980.mp4

**Comment by Pro0rbit** [comment]
I also have this issue Please Update a Fix. Still trying to use it but sit in the ground or feet are under the ground with standing/moving.

**Comment by Rokudo03** [comment]
can't help but I have the same problem here too.
thank you so mutch for your great work, have a nice day.
