### ISSUE TITLE
Support for model scale like 0.15

### ISSUE THREAD

**Issue by zzarkness** [yoship1639/ValheimVRM#2]
Hello, thanks for the mod.
Can you make the mod using the value like 0.15, 0.26 ECT...
The 0.1 are too small and 0.2 are too large, but if I set it to 0.15, the model become very huge.

**Comment by yoship1639** [comment]
Thanks for the post.
Please check ver 1.0.3 as I have just updated the settings related.

[https://github.com/yoship1639/ValheimVRM/releases/tag/ver1.0.3](https://github.com/yoship1639/ValheimVRM/releases/tag/ver1.0.3)
