### ISSUE TITLE
valheimvrm visual enhancements gui/ingame adjustments. have made 520 vrms for people to use.

### ISSUE THREAD

**Issue by NorgerLegacy** [yoship1639/ValheimVRM#20]
Have tried to reach out to you but never get a response. i'll try here.
Love the mod, currently have created over 350 vrm characters. My friend was nice enough to convert this mod to have a in game gui where i change/adjust all settings, swap character models live in game no more closing adjusting and relaunching.  I hang out on the odin plus discord since they are the most active group for valheim mods if you choose to talk. their look up there mods on thunderstore and it has link to the discord. 

here is a link of a low resolution video showing what it can do. 
https://streamable.com/0dfguc

**Comment by venusvariation** [comment]
Sorry for the late reply!

**Comment by NorgerLegacy** [comment]
Yoship would love to get this feature Released for all  users to use. As this would draw more users in to use the mod with the ability to not rename the vrms to match character name, swap while in game, adjust weapon placement, scale of character, all live in game and effects taken immediately. It simplifies the process therefore more people will try the mod.
 I have now made over 430+ vrms for people to use over on [ModVault.xyz](https://modvault.xyz)

**Comment by NorgerLegacy** [comment]
> 

?

**Comment by NorgerLegacy** [comment]
> Sorry for the late reply!
> […](#)
> Sent from my iPhone
> On Dec 31, 2021, at 12:23 AM, Norger ***@***.***> wrote: ﻿ Have tried to reach out to you but never get a response. i'll try here. Love the mod, currently have created over 350 vrm characters. My friend was nice enough to convert this mod to have a in game gui where i change/adjust all settings, swap character models live in game no more closing adjusting and relaunching. I hang out on the odin plus discord since they are the most active group for valheim mods if you choose to talk. their look up there mods on thunderstore and it has link to the discord. here is a link of a low resolution video showing what it can do. https://streamable.com/0dfguc — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.

??

**Comment by NorgerLegacy** [comment]
now over 475 vrm models i have uploaded to modvault

**Comment by fairlylogical** [comment]
> modvault.xyz/users/632/files
well hot damn, you sir are a madlad !
