### ISSUE TITLE
mtoon shader option cull defaults to cull back

### ISSUE THREAD

**Issue by linthiel** [yoship1639/ValheimVRM#3]
Hello,

This might be one of the material issues you mentioned, but on my vrm model, it seems that in-game, the shader defaults to cull back, any way to have this set to cull none in the settings config or somewhere else?

**Comment by yoship1639** [comment]
Thanks for the question.
The culling setting doesn't seem to exist in Valheim's standard shaders. So it is not possible to turn off culling.

**Comment by linthiel** [comment]
This was fixed with one of the later versions forgot to respond
