### ISSUE TITLE
some error occurred

### ISSUE THREAD

**Issue by jackjnsd203** [yoship1639/ValheimVRM#4]
Thankyou for the great mod! But some error occurred.
How do I fix it?

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ValheimVRM.EyeSync.Update () (at <a953df2105784ab1b910b1a267e96dde>:0)

thankyou

**Comment by yoship1639** [comment]
Thank you for your report. Fixed this issue in ver1.0.9.
