### ISSUE TITLE
Build 

### ISSUE THREAD

**Issue by astro5743** [yoship1639/ValheimVRM#5]
日本語で失礼致します。
Valheimも取り敢えず全ボスを倒し終わりmodを導入し、vrmに興味を惹かれこちらも導入させて頂きました。
vrm的な問題なのかは自分自身では判断しかねてる事で、例えば2×2の内寸法の煙突を建築中とした場合
アバターが内側に居て作業している状態で頭や髪が透けずポインターがまるで見えません。
デフォルトのアバターの場合は早い段階で透けると言うよりカメラ視点が変わり、頭等が気にならない様になってます。
vrmアバターデーターの問題なのか、こちらで改善出来る事なら改善願います。

**Comment by yoship1639** [comment]
ご報告ありがとうございます。
ver1.0.9にてオリジナルモデル同様カメラが近い時にVRMモデルが透けるように致しました。
