### ISSUE TITLE
Request, not issues

### ISSUE THREAD

**Issue by astro5743** [yoship1639/ValheimVRM#6]
御世話に成ります。
近い場所でアバターが透ける対応、有難う御座いました。

全くゲーム開発やデーター系に疎いズブの素人考えで、
vrmとか出来る人は何でも出来るんじゃね？的な事からの要望なのですが
vrmでポインターの色や形を変える事は出来ないでしょうか？
雪山で雪が降る状況等の場面で白いポインターは的が絞りにくいので色が変えれたらと・・・。
人任せで申し訳御座いませんが可能であれば御願い致します。

**Comment by yoship1639** [comment]
VRMとは関係のない機能なので棄却いたします
