### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Altwort** [yoship1639/ValheimVRM#7]
Hello,

In gaming，not problem in play ,just the cmd error code report endless  

[Info   : Unity Log] [ValheimVRM] RightHandEuqipPos: (0.0, 0.0, 0.0)
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ValheimVRM.Patch_VisEquipment_SetLeftHandEquiped.Postfix (VisEquipment __instance) (at <3544879eab8d48b7a88810c178c68e85>:0)
(wrapper dynamic-method) VisEquipment.DMD<VisEquipment::SetLeftHandEquiped>(VisEquipment,int,int)
VisEquipment.UpdateEquipmentVisuals () (at <64e3050735a54dbb8762d6e3432a1162>:0)
VisEquipment.UpdateVisuals () (at <64e3050735a54dbb8762d6e3432a1162>:0)
VisEquipment.Update () (at <64e3050735a54dbb8762d6e3432a1162>:0)

**Comment by DatapawWolf** [comment]
Can confirm. Also happening to me.

**Comment by yoship1639** [comment]
Oops. Thank you. I'll fix it soon.
