### ISSUE TITLE
ver1.0.10 or later 

### ISSUE THREAD

**Issue by astro5743** [yoship1639/ValheimVRM#8]
御世話に成ります。
ver1.0.10以降、非常に重いです。
ver1.0.10使用時はゲーム開始ワールドセーブ2回目、約10分でカクカク状態になり
ver1.0.11でも同じ状態の他にゲームが終了出来ません。
終了時固まってタスクマネージャーで終了させないといつまで待っても終わりません。
自分はmodも何種類か使用してますが、ver1.0.9では上記の状態にはなりません。
現在ver1.0.9へ戻してゲームしてます。

**Comment by yoship1639** [comment]
ご報告ありがとうございます。
ver1.0.12にて上記問題を修正しました。
ご確認いただければ幸いです。
